--- 
abstract: Restart Firefox/Thunderbird
author: Toru Yamaguchi <zigorou@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MozRepl-Plugin-Restart
no_index: 
  directory: 
    - inc
    - t
requires: 
  Getopt::Long: 0
  MozRepl: 0.02
  Pod::Usage: 0
version: 0.02
